version: "3.6"

services:
  gate:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app_client
      - app_server
    ports:
      - 8080:80

  mongo:
    image: mongo:4-xenial
    restart: always
    volumes:
      - ./db:/data/db

  app_client:
    image: carcinogen75/noteshub-client
    expose:
      - 80

  app_server:
    image: carcinogen75/noteshub-server
    env_file: .server.env
    environment:
      MONGO_URL: mongodb://mongo:27017/noteshub
      PORT: 80
    expose:
      - 80
    depends_on:
      - mongo
    links:
      - mongo
    restart:
      on-failure

